E-Retalling_Portal/Models/Discount.cs
using System.ComponentModel.DataAnnotations;

namespace E_Retalling_Portal.Models
{
	public class Discount
	{
		public int id { get; set; }
		[Required,MaxLength(100)]
		public string name { get; set; }
		[Required, MaxLength(2000)]
		public string startDate { get; set; }
		public string endDate { get; set; }
		public int value { get; set; }
		public int shopId { get; set; }
		public int? deleteAt { get; set; }
		public Shop shop { get; set; }
		public List<ProductDiscount>? productDiscounts { get; set; }





	}
}

E-Retalling_Portal/Controllers/SellerShopManager/CreateShopController.cs
using E_Retalling_Portal.Models.Enums;
using E_Retalling_Portal.Models;
using Microsoft.AspNetCore.Mvc;
using E_Retalling_Portal.Models.Query;
using E_Retalling_Portal.Controllers.Filter;

namespace E_Retalling_Portal.Controllers.SellerShopManager
{
	public class CreateShopController : Controller
	{
		[TypeFilter(typeof(ShopOwnerRoleFilter))]
		public IActionResult Index()
		{
			var accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());

			
				using (var DbContext = new Context())
				{
					Shop? shop = DbContext.Shops.GetShopbyAccId(accId.Value).FirstOrDefault();
					if (shop == null)
					{
						return RedirectToAction("CreateShop");
					} else return RedirectToAction("Index", "ShopDashBoard");
			}

		}
		public IActionResult NoShop()
		{
			return View("Views/SellerShopManager/CreateShop/NoShop.cshtml");
		}

		public IActionResult CreateShop()
		{
			return View("Views/SellerShopManager/CreateShop/CreateShop.cshtml");
		}

		[HttpPost]
		public IActionResult CreateShopProcess(Shop shop)
		{
			if (ModelState.IsValid)
			{
				int? accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
				using (var context = new Context())
				{
					if (context.Shops.GetShopByName(shop.name).FirstOrDefault() == null)
					{
						shop.accountId = accId.Value;
						shop.statusId = 1;
						context.Shops.Add(shop);
						context.SaveChanges();
						return RedirectToAction("Index", "ShopDashBoard");
					}
					else
					{
						ViewBag.ErrorName = "This name has been used";
						ViewBag.Shop = shop;
						return View("Views/SellerShopManager/CreateShop/CreateShop.cshtml");
					}

				}

			}
			else return View("Views/Shared/ErrorPage/Error500.cshtml");
		}
	}
}

E-Retalling_Portal/Controllers/SellerShopManager/DiscountManagerController.cs
using E_Retalling_Portal.Models.Enums;
using E_Retalling_Portal.Models;
using Microsoft.AspNetCore.Mvc;
using E_Retalling_Portal.Controllers.Filter;
using E_Retalling_Portal.Models.Query;
using E_Retalling_Portal.Services.ExtendService;
using Microsoft.IdentityModel.Tokens;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.CodeAnalysis;
using System.ComponentModel.DataAnnotations;
using Microsoft.Build.Evaluation;
namespace E_Retalling_Portal.Controllers.SellerShopManager
{
    [TypeFilter(typeof(ShopOwnerRoleFilter))]
    [TypeFilter(typeof(HaveShopFilter))]
    [TypeFilter(typeof(DiscountFilter))]
    public class DiscountManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ViewProductUnDiscount()
        {
            int? accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
            if (accId == null)
            {
                return View("Views/Shared/ErrorPage/Error500.cshtml");

            }

            using (var context = new Context())
            {
                var shop = context.Shops.GetShopbyAccId(accId.Value).FirstOrDefault();
                List<Product> products = new List<Product>();
                List<Discount> discounts = context.Discounts.GetDiscountByShop(shop.id).ToList();
                List<ProductDiscount> productDiscount = new List<ProductDiscount>();
                List<Tuple<int, int?>> productItemvalues = new List<Tuple<int, int?>>();
                if (!discounts.IsNullOrEmpty())
                {
                    foreach (var discount in discounts)
                    {

                        var items = context.ProductDiscounts.GetProductDiscountByDiscountId(discount.id).ToList();
                        foreach (var item in items)
                        {
                            productDiscount.Add(item);
                        }
                    }
                }

                foreach (var discount in productDiscount)
                {
                    if (discount != null)
                    {
                        productItemvalues.Add(Tuple.Create(discount.productId, (int?)discount.productItemId));
                    }
                    
                }

                List<Product> productsStore = context.Products.GetProductsByShop(shop.id).ToList();
                List<Tuple<int, int?>> values = new List<Tuple<int, int?>>();
                foreach (var product in productsStore)
                {
                    List<ProductItem> items = context.ProductItems.GetProductItem(product.id).ToList();
                    if(items.IsNullOrEmpty())
                    {
                        values.Add(Tuple.Create(product.id, (int?)null));
                    }
                    else
                    {                        
                        foreach (var productItem in items)
                        {
                            values.Add(Tuple.Create(product.id, (int?)productItem.id));
                        }
                    }
                    
                }

                foreach (var productItemvalue in productItemvalues)
                {
                    if (values.Contains(productItemvalue))
                    {
                        values.Remove(productItemvalue);
                    }
                }

                List<Product> viewProducts = new List<Product>();
                foreach (var value in values)
                {
                    if (!viewProducts.Contains(context.Products.GetProductById(value.Item1).FirstOrDefault()))
                    {
                        viewProducts.Add(context.Products.GetProductById(value.Item1).FirstOrDefault());
                    }
                    
                }

                ViewBag.products = viewProducts;
            }

            return View("/Views/SellerShopManager/Discount/ViewProductUnDiscount.cshtml");
        }

        public IActionResult UnDiscountVariation(int productId)
        {
            int? accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
            if (accId == null)
            {
                return View("Views/Shared/ErrorPage/Error500.cshtml");

            }

            using (var context = new Context())
            {
                List<ProductItem> products = context.ProductItems.GetProductItem(productId).ToList();
                List<ProductDiscount> productDiscounts = context.ProductDiscounts.GetProductDiscountByProductId(productId).ToList();
                List<ProductItem> productItemsDiscount = new List<ProductItem>();
                foreach (var discount in productDiscounts)
                {
                    if (discount.productItemId != null)
                    {
                        productItemsDiscount.Add(context.ProductItems.GetProductItemByProductItemId(discount.productItemId.Value).FirstOrDefault());

                    }

                }
                if (!productItemsDiscount.IsNullOrEmpty())
                {
                    foreach (var discount in productItemsDiscount)
                    {
                        if (products.Contains(discount))
                        {
                            products.Remove(discount);
                        }
                    }
                }
                

                ViewBag.images = context.Images.GetImagesByProductId(productId).ToList();
                ViewBag.productId = productId;
                ViewBag.productItems = products;

            }

            return View("/Views/SellerShopManager/Discount/UnDiscountVariation.cshtml");
        }

        public IActionResult ViewProductOnDiscount()
        {
            int? accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
            if (accId == null)
            {
                return View("Views/Shared/ErrorPage/Error500.cshtml");

            }

            using (var context = new Context())
            {
                var shop = context.Shops.GetShopbyAccId(accId.Value).FirstOrDefault();
                List<Product> products = new List<Product>();
                List<Discount> discounts = context.Discounts.GetDiscountByShop(shop.id).ToList();
                List<ProductDiscount> productDiscount = new List<ProductDiscount>();

                if (!discounts.IsNullOrEmpty())
                {
                    foreach (var discount in discounts)
                    {

                        var items = context.ProductDiscounts.GetProductDiscountByDiscountId(discount.id).ToList();
                        foreach (var item in items)
                        {
                            productDiscount.Add(item);
                        }
                    }
                }

                foreach (var discount in productDiscount)
                {
                    if (discount != null && !products.Contains(context.Products.GetProductById(discount.productId).FirstOrDefault()))
                    {
                        products.Add(context.Products.GetProductById(discount.productId).FirstOrDefault());
                    } 
                }
                List<Discount> discountItem = new List<Discount>();
                foreach (var product in products)
                {
                    if (!product.isVariation)
                    {
                        ProductDiscount pd = context.ProductDiscounts.GetProductDiscountByProductIdAndProductItemId(product.id, null).FirstOrDefault();
                        var discount = context.Discounts.GetDiscountByDiscountId(pd.discountId).FirstOrDefault();
                        discountItem.Add(discount);
                    }
                    else discountItem.Add(null);
                   
                }
                ViewBag.discount = discountItem;
                ViewBag.products = products;
            }

            return View("/Views/SellerShopManager/Discount/ViewProductOnDiscount.cshtml");
        }

        public IActionResult DiscountVariation(int productId)
        {
            int? accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
            if (accId == null)
            {
                return View("Views/Shared/ErrorPage/Error500.cshtml");

            }

            using (var context = new Context())
            {
                List<ProductItem> products = context.ProductItems.GetProductItem(productId).ToList();
                if (products.IsNullOrEmpty())
                {
                    return View("Views/Shared/ErrorPage/Error500.cshtml");
                }
                List<ProductDiscount> productDiscounts = context.ProductDiscounts.GetProductDiscountByProductId(productId).ToList();
                List<ProductItem> productItemsDiscount = new List<ProductItem>();
                foreach (var discount in productDiscounts)
                {
                    if (discount.productItemId != null)
                    {
                  
                        productItemsDiscount.Add(context.ProductItems.GetProductItemByProductItemId(discount.productItemId.Value).FirstOrDefault());

                    }

                }

                List<Discount> discountItem = new List<Discount>();
                foreach (var productItem in productItemsDiscount)
                {
                    ProductDiscount pd = context.ProductDiscounts.GetProductDiscountByProductIdAndProductItemId(productId, productItem.id).FirstOrDefault();
                    var discount = context.Discounts.GetDiscountByDiscountId(pd.discountId).FirstOrDefault();
                    discountItem.Add(discount);
                }

                ViewBag.images = context.Images.GetImagesByProductId(productId).ToList();
                ViewBag.productId = productId;
                ViewBag.productItems = productItemsDiscount;

E-Retalling_Portal/Controllers/SellerShopManager/ShopChartController.cs
using Microsoft.AspNetCore.Mvc;
using E_Retalling_Portal.Models.ChartModel;
using System.Collections.Generic;
using E_Retalling_Portal.Models;
using E_Retalling_Portal.Models.Enums;
using E_Retalling_Portal.Models.Query;
using Microsoft.IdentityModel.Tokens;
using E_Retalling_Portal.Controllers.Filter;

namespace E_Retalling_Portal.Controllers.SellerShopManager
{
    public class ShopChartController : Controller
    {
        [TypeFilter(typeof(ShopOwnerRoleFilter))]
        [TypeFilter(typeof(HaveShopFilter))]
        public IActionResult ViewShopChart()
        {
            var context = new Context();
            int? accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
            var shop = context.Shops.GetShopbyAccId(accId.Value).FirstOrDefault();
            DateTime now = DateTime.Now;
            int currentYear = now.Year;
            DateTime createAt = DateTime.Parse(shop.createdAt);
            int createYear = createAt.Year;
            List<int> year = new List<int>();
            if (currentYear - createYear >= 3)
            {
                for (int i = 0; i < 3; i++)
                {
                    year.Add(currentYear - i);
                }
            }
            else
            {
                for (int i = 0; i < currentYear - createYear; i++)
                {
                    year.Add(currentYear - i);
                }
                if (year.IsNullOrEmpty())
                {
                    year.Add(createYear);
                }
            }
            ViewBag.years = year;
            return View("/Views/SellerShopManager/ShopChart/ViewShopChart.cshtml");
        }

        [HttpGet]
        public IActionResult LoadChartData(string yearString)
        {
            string[] monthsString = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
            if (string.IsNullOrEmpty(yearString))
                return Json(new { error = "Invalid year" });

            using (var context = new Context())
            {
                int? accId = HttpContext.Session.GetInt32(SessionKeys.AccountId.ToString());
                var shop = context.Shops.GetShopbyAccId(accId.Value).FirstOrDefault();
                List<Product> products = context.Products.GetProductsByShopNoNull(shop.id).ToList();
               
                double[] data = new double[monthsString.Length];
                double[] average = new double[monthsString.Length];
                double[] other = new double[monthsString.Length];
                double countSale = 0;
                double countFee = 0;

                int year = DateTime.ParseExact(yearString.Trim(), "yyyy", null).Year;
                for (int i = 0; i < monthsString.Length; i++)
                {
                    countSale = 0;
                    countFee = 0;
                    int day = i + 1;
                    int month = DateTime.ParseExact(monthsString[i].Trim(), "MMMM", null).Month;
                    List<Order> orderInMonth = context.Orders.GetOrderByYearMonth(year, month).ToList();

                    foreach (var order in orderInMonth)
                    {
                        List<OrderItem> orderItems = context.OrderItems.GetOrderItemByOrderId(order.id).ToList();
                        foreach (var item in orderItems)
                        {
                            countFee = 0;
                            if (item.shippingStatus.ToString().Equals("delivered", StringComparison.OrdinalIgnoreCase))
                            {
                                if (products.Contains(context.Products.GetProductByIdNoNull(item.productId).FirstOrDefault()))
                                {
                                    double today = item.price;
                                    countFee += today * item.transactionFee / 100;
                                    countSale += today - countFee;
                                    Console.WriteLine($"don = {today}, fee = {countFee}, sale = {countSale}");
                                }
                            }

                        }
                        data[i] = countSale;
                    }

                }
                var labels = monthsString;
                var sales = data;
                return Json(new { labels, sales});
            }

        }

    }



}

E-Retalling_Portal/Views/SellerShopManager/Discount/ChooseDiscountProduct.cshtml
@{
    ViewData["Title"] = "ChooseDiscountProduct";
    Layout = "~/Views/Shared/ShopManagerSideBarLayout.cshtml";
}
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
<style>
    .row-img{
        width:80px;
        height:80px;
    }
</style>
<div class="content m-4 pb-3">

    <div class="row p-4">
        <div class="col-12">
            <table id="myTable" class="display">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>StartDate</th>
                        <th>EndDate</th>
                        <th>Value(%)</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.discount)
                    {
                        <tr>
                            <td>@item.name</td>
                            <td>@item.startDate</td>
                            <td>@item.endDate</td>
                            <td>@item.value</td>

                            <td>
                                <a href="ChooseDiscountProductProcess?discountId=@item.id" class="text-primary font-weight-bold text-xs btn">
                                    Apply Discount
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
<script>

    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

E-Retalling_Portal/Views/SellerShopManager/Discount/DiscountVariation.cshtml
@{
    ViewData["Title"] = "DiscountVariation";
    Layout = "~/Views/Shared/ShopManagerSideBarLayout.cshtml";
}
@{
    var products = ViewBag.productItems as List<ProductItem>;  // Adjust `ProductModel` to your product model type
    var discounts = ViewBag.discount as List<Discount>;  // Adjust `DiscountModel` to your discount model type
    var count = Math.Min(products.Count, discounts.Count);  // Use the smaller count to avoid out-of-bounds errors
    var today = DateTime.Today; // Today's date, without time component
}
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
<style>
    .row-img {
        width: 80px;
        height: 80px;
    }

    .image-radio {
        display: none;
    }

    .image-radio-label {
        display: inline-block;
        cursor: pointer;
    }

    .image-radio-label img {
        width: 80px;
        height: auto;
        margin: 5px;
        border: 2px solid transparent;
     }

    .image-radio:checked + .image-radio-label {
        border: 2px solid blue;
    }
    label{
        margin-left:5px;
    }
</style>
<div class="content m-4 pb-3">

    <div class="row p-4">
        <div class="col-12">
            <table id="myTable" class="display">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Attribute</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Active</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < count; i++)
                    {
                        var product = products[i];
                        var discount = discounts[i];
                        <tr>
                            <td><img class="row-img" src="~/productImages/@product.image.imageName" /></td>
                            <td>@product.attribute</td>
                            <td>@product.price</td>
                            <td>@product.quantity</td>
                            @if (today >= DateTime.Parse(discount.startDate.ToString()) && today <= DateTime.Parse(discount.endDate.ToString()))
                            {
                                <td class="text-primary font-weight-bold text-xs">Active</td>
                            }
                            else
                            {
                                <td class="text-danger font-weight-bold text-xs">Not Active</td>
                            }
                            <td>
                                <a href="ViewDetailDiscount?productId=@ViewBag.productId&&productItemId=@product.id" class="text-primary font-weight-bold text-xs btn">
                                    Detail Discount
                                </a>|
                                <a href="#" class="text-danger font-weight-bold text-xs" data-bs-toggle="modal" data-bs-target="#deleteModal" onclick="sendDataToModal(@ViewBag.productId,@product.id)">
                                    Stop Discount
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <a href="@Url.Action("ViewProductOnDiscount","DiscountManager")" class="btn btn-dark ms-4 btn-pill text-uppercase">
        Back
    </a>
</div>

<!-- Delete Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModal">Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-danger text-uppercase font-weight-bold">
                Confirm Stop
            </div>
            <form action="StopDiscount">
                <input type="hidden" name="productId" value="" id="delete-product-id" />
                <input type="hidden" name="productItemId" value="" id="delete-product-item-id" />
                <div class="modal-footer">
                    <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Stop</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
<script>
    function sendDataToModal(productId, productitemId) {
        $('#delete-product-id').val(productId);
        $('#delete-product-item-id').val(productitemId);
    }

    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

E-Retalling_Portal/Views/SellerShopManager/Discount/UnDiscountVariation.cshtml
@{
    ViewData["Title"] = "UnDiscountVariation";
    Layout = "~/Views/Shared/ShopManagerSideBarLayout.cshtml";
}
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
<style>
    .row-img {
        width: 80px;
        height: 80px;
    }

    .image-radio {
        display: none;
    }

    .image-radio-label {
        display: inline-block;
        cursor: pointer;
    }

    .image-radio-label img {
        width: 80px;
        height: auto;
        margin: 5px;
        border: 2px solid transparent;
     }

    .image-radio:checked + .image-radio-label {
        border: 2px solid blue;
    }
    label{
        margin-left:5px;
    }
</style>
<div class="content m-4 pb-3">

    <div class="row p-4">
        <div class="col-12">
            <table id="myTable" class="display">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Attribute</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.productItems)
                    {
                        <tr>
                            <td><img class="row-img" src="~/productImages/@item.image.imageName" /></td>
                            <td>@item.attribute</td>
                            <td>@item.price</td>
                            <td>@item.quantity</td>
                            <td>
                                <a href="ChooseDiscountProduct?productId=@ViewBag.productId&&productItemId=@item.id" class="text-primary font-weight-bold text-xs btn">
                                    Discount
                                </a>                               
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <a href="@Url.Action("ViewProductUnDiscount","DiscountManager")" class="btn btn-dark ms-4 btn-pill text-uppercase">
        Back
    </a>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

E-Retalling_Portal/Views/SellerShopManager/Discount/ViewListDiscount.cshtml
@{
    ViewData["Title"] = "ViewListDiscount";
    Layout = "~/Views/Shared/ShopManagerSideBarLayout.cshtml";
}
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
<style>
    .row-img{
        width:80px;
        height:80px;
    }
</style>
<div class="content m-4 pb-3">

    <div class="row p-4">
        <div class="col-12">
            <div class="row">
                <div class="d-flex justify-content-between mb-3">
                    <button type="button" class="btn btn-dark btn-pill text-uppercase" onclick="location.href='@Url.Action("ViewProductUnDiscount","DiscountManager")'">
                        Apply Discount
                    </button>
                    <button type="button" class="btn btn-dark btn-pill text-uppercase" onclick="location.href='@Url.Action("CreateDiscount","DiscountManager")'">
                        Create Discount
                    </button>
                </div>


            <table id="myTable" class="display">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>StartDate</th>
                        <th>EndDate</th>
                        <th>Value</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.discount)
                    {
                        <tr>
                            <td>@item.name</td>
                            <td>@item.startDate</td>
                            <td>@item.endDate</td>
                            <td>@item.value</td>

                            <td>
                                <a href="EditDiscount?discountId=@item.id" class="text-primary font-weight-bold text-xs btn">
                                    Edit
                                </a>|
                                <a href="#" class="text-danger font-weight-bold text-xs" data-bs-toggle="modal" data-bs-target="#deleteModal" onclick="sendDataToModal(@item.id)">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Delete Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModal">Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-danger text-uppercase font-weight-bold">
                Confirm delete
            </div>
            <form action="DeleteDiscount">
                <input type="hidden" name="discountId" value="" id="deleteDiscount" />
                <div class="modal-footer">
                    <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
<script>
    function sendDataToModal(id) {
        $('#deleteDiscount').val(id);
    }

    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>